### ISSUE TITLE
Feature: User can create a contact

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/Drip-Email-System#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create contact.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
A user will be able to create a contact.

I plan on creating a contact entry page, so that a user of this application will be able to enter _some_ information that pertains to a contact. Specifically first name, last name, company name, e-mail, and phone number. As the application is e-mail based, the other fields that exist for the contact are primarily for show. The e-mail field, and the contact first name, last name, and company field, are the four pivotal fields that will receive information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature_1](https://user-images.githubusercontent.com/51938797/119423189-8f0d9080-bcb7-11eb-862f-5edc3b9994a5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### :cloud: Server
- [x] Update server/index.js
- [x] Handle all errors and respond to the client.
- [x] Integrate client calls with database inserts

### 🐘 Database

- [x] Update `schema.sql` to create a 'contacts' table.
- [x] contacts table should have an id column. (integer field)
- [x] contacts table should have first name column. (text field)
- [x] contacts table should have last name column. (text field)
- [x] contacts table should have company name column. (text field)
- [x] contacts table should have email column. (text field)
- [x] contacts table should have phone number column. *(
- [x] Update `data.sql` to ...

### ⚡ Client

- [x] Create a component to display the contact creation page.
- [x] Add functionality that will absorb texts from fields, and send it into the database.
 - [x] once this is complete, the text fields will be cleared.
 - [x] Style elements according to the wireframe.

### 🧑‍⚕️ Clean Up

- [x] Create a component that will send information into the databse.
- [x]  The email field should validate and dynamilcally reject any information that does not conform to standard e-mail entry format.
- [x] A generic, blank picture should be included for contacts.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
