### ISSUE TITLE
Refactor: Tim D. Code Review - Cleanup

### ISSUE THREAD

**Issue by thebearingedge** [Smith-Steve/Drip-Email-System#101]
Hi Steve, here's a code review as we discussed via Slack. I'll do a separate UI review. The cleanup should come first as it's _much_ easier to make behavioral and visual changes to the code when the code is clean. In some cases, I point to specific lines of code, but you should be looking out for these issues throughout the entire code base.

As always, make sure you test your app after each change to confirm that it still works as expected. Also commit after each change.

## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [ ] First things first, all file and directory names should be `lower-kebab-case`. I looked in `server/lib/` and there is a seemingly random mix of casing conventions like `camelCase` and whatever `nodeMailer-transporter.js` is. `nodemailer` is one word, all lowercase. Every file and folder in your entire project should be `lower-kebab-case`.
- [ ] Next, sort your `require()` and `import` statements. Built-in Node.js modules and npm packages should come first, followed by your own modules. This should be applied to every file in your project. An example of disorganized imports is [here](https://github.com/Smith-Steve/Drip-Email-System/blob/master/server/index.js#L2).
- [ ] Your codebase should have absolutely zero chunks of commented out sections. I found a huge one pretty quickly [here](https://github.com/Smith-Steve/Drip-Email-System/blob/cae56224411f1cffaec20604a0deb071afa061d7/server/index.js#L342).
- [ ] You have a lot of repetitive error handling code in your [`server/index.js`](https://github.com/Smith-Steve/Drip-Email-System/blob/cae56224411f1cffaec20604a0deb071afa061d7/server/index.js#L34). Review the `express-error-handling` exercise and move your `errorMiddleware` registration to just before your `app.listen()`.
- [ ] Your [SQL code](https://github.com/Smith-Steve/Drip-Email-System/blob/cae56224411f1cffaec20604a0deb071afa061d7/server/index.js#L194) should be indented for readability.
- [ ] You have an `app.jsx` that simply renders `home.jsx`. Cut out the middleman. Just make Home your App (and rename/remove files accordingly).
- [ ] I found a few empty files in your `client/` directory. Avoid ever merging anything into your `master` branch that isn't done yet.
- [ ] You are using a seemingly random mix of property initializers with arrow functions and [bound prototype methods](https://github.com/Smith-Steve/Drip-Email-System/blob/cae56224411f1cffaec20604a0deb071afa061d7/client/pages/components/flight/flights.jsx#L8) in your classes. You have two options:
    - Stick with prototype methods only (no arrow methods as they are not officially part of standard JavaScript yet). Only bind methods that break if you don't bind them.
    - Use the arrow methods but add a babel transform to make sure that they get converted into standard JavaScript
- [ ] Use ES6 classes instead of [constructor functions.](https://github.com/Smith-Steve/Drip-Email-System/blob/cae56224411f1cffaec20604a0deb071afa061d7/client/pages/lib/email-post.js#L1)

**Comment by Smith-Steve** [comment]
@thebearingedge 

Tim, I have double checked this and have gotten everything. A question for you. I'm going to Slack this to you as well.

1.  On check mark 8, you said "You seemingly use a random mix of property initilizers ....". I was using the arrow methods that I did not intend on using _outside_ of the component in question. Beyond that, it is true that there was no rhyme or reason to why I was using bound prototype methods over arrow functions. What is this not reason enough?

**Comment by thebearingedge** [comment]
@Smith-Steve Hi Steve! The methods of your components are generally only going to be calling each other or called by the React framework. The main reason to choose an "arrow method" is to avoid having to bind it in your constructor. The JavaScript engine interprets them as follows.

This is what you write:
```js
class Example {
  constructor() {
   
  }
  aMethod = () => {
  }
}
```

And this is how the JavaScript engine interprets it:

```js
class Example {
  constructor() {
    this.aMethod = () => {
  }
}
```

It's a new language feature that is very near being official, but it's not quite there yet. It's at stage 3 of the proposal process.

https://github.com/tc39/proposal-class-fields
