### ISSUE TITLE
Feature: User can view a list of scripts

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/Drip-Email-System#18]
## User can view a list of scripts they have created within the script creation page.

> ##### What capability will users have when this feature is merged?
After the user creates a script, they will be able to view it within the script creation page. Additionally, any previous scripts that have been created will also be present in the list,.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Scripts are meant to be independent of flights, so that a user can 'plug and play' them into different flights they create over time. They are meant for re-use over time. Their contents can have themes which are yearly, quarterly or whatever which the user may want to avail themselves of.

An important part of this, will be for the user to understand what scripts already exist, so they can understand what scripts do not. This will allow them to know whether or not they need to create a new one. This list will help them make that decision. Additionally, it is from this list, that users will access the features that will allow them to add/delete and eventually edit e-mails within the list.

Although not included in this feature, this feature is incidental to the user being able to manage an individual script. This page, will be the users route to manage an individual script.

## 🖼️ Wireframes

Plan is as follows:

 - No DB work for this feature.
 - Create GET call by ID.
 - Create new component for front end in the following order:
  - Set up React/CSS classes to conform to existing layout paradigm and ensure there is no alteration to other components.
  - Ensure once new submission of script is made, it is displaying on the front end automatically.

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Figma](https://user-images.githubusercontent.com/51938797/120235766-9f6dc000-c20f-11eb-9d7c-6349d9eafc80.png)

Concerns: Should I add button to list anyway? Button will lead user to next feature. It will be easy and smooth to add it now.
- Should I add this to existing component? Or create a new component that houses both of the display list and the entry form, and render that on the home page? I'm thinking working with one component will be easier.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] There is nothing new being added to the database for this feature.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Add a GET Route by ID so that when a flight is created, it is automatically added to the list.

### ⚡ Client

- [x] Create a component to display a list of all existing flights.
- [x] Update that component to display the newest addition to the client.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
