### ISSUE TITLE
Feature: User can view manage script page

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/Drip-Email-System#19]
## ⚙️User can view the manage script page.

> ##### What capability will users have when this feature is merged?
User will be able to view manage script page.

## 📐 Functionality
Scripts contain a series of e-mails. There are two types of e-mails. There are initial e-mails, and response e-mails, or e-mails that are sent as replys' to the initial e-mail. Each email must follow the one preceeding it.

It is from this page that the user will be able to initiate the creation of the emails.

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![User Can View Manage Script](https://user-images.githubusercontent.com/51938797/120238779-bf05e800-c211-11eb-933d-734ef8dd7407.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

As this feature is restricted to _viewing only_ a script, it will not include any database functionality.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] As this feature is restricted only to _viewing_ the contents of a script, and as of present the creation of e-mails does not exist, there are no server functions to be written.

### ⚡ Client

- [x] Create a component to display the view manage script page, and what is inside of it - which for this feature will be nothing.
- [x] Leave the create button within this feature, so that it will be easy to initiate the creation of e-mails for the next feature.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
