### ISSUE TITLE
Feature: User can create a flight

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/Drip-Email-System#2]
## 📐 Functionality
User will be able to create a flight. 

A flight contains scripts and contacts. Scripts contain email chains. Contacts contain e-mail addresses, this allows for the emails to reach those contacts.

Flights are the 'final block' that a user uses to assemble and send emails to contacts. Flights are important.

User will enter a name for the flight into the text field. After that, they will enter a list of single word, comma separated values that represent what the theme of the flight is. Then, the user will enter the name of the script they whish to use. This script must have been previously created.

They will then select the 'create' button, which will initiate the creation of the flight. There are three outcomes:

A.) The creation of the flight was successful, and they receive feedback from the system (an alert for now, later a toaster) letting them know that it was created.

B.) A generic failure message.

C.) A failure message (an alert for now, a toaster later) letting them know that the reason it was not created was because the script they attempted to use does not exist.

## Plan of Approach

 Plan is as follows:
  - Create DB.
  - Insert Dummy Material into DB.
  - Display Dummy Data via HTTPie.
  - Create POST call.
  - Create new component for front end in the following order:
     - Set up Router Functionality  so component can be viewed.
      - First Create Static Text that is the header of component.
      - Then Create React Element that outlines Form. Then Create Form.
      - Add Text Prompts For input fields Form.
      - Add Input Fields.
      - Add Buttons.
      - Set up react elements/css classes to conform to existing layout paradigm and ensure there is no alteration of the layout of other components.
      - Add Form Controls.
      - Check to see if form is submitting from front end to back end.
      - Add Import Statements.
      - Add relevant code to import statements.

Concerns: User will be able to add a script to a flight, but only if it is a valid and existing script. What is the proper way to ensure
that we are only getting valid script names from the user? Should they be exact matches based upon text? Should a get request be fired, search the database for similar values? (I recall % working for similarity in texts for dbs.) and then return the scriptId?

I am not clear on what kind of get request will have to be used to that table, what kind of result it will return, and how to return the proper id from the scripts table into the flights table. 

 - is Just the SciprtId enough?
 - How do I get the script Id?
 - There was a lesson that demonstrated foreign keys, which one?
 - Is there a way to provide real time feedback to the user whether or not the value they provided exists or not? Right on the form? This would be a more smooth user experience.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Figma Photo](https://user-images.githubusercontent.com/51938797/120017061-3fbaaf00-bf9a-11eb-93e5-d0289c266716.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...
- [x] create flights table.
- [x] flights table should have an id column to identify the flight. (integer field)
- [x] flights table should have a topics column that contains topics (text field).
- [x] flights table should have a name column to identify the name of the flight. (text field)
- [x] flights table should have a scriptsId column within it. (Integer field, foreign key. How to proceed?)

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Add a GET route to back end that provides list of existing scripts.
-  [x] Post & Proper Guards.

### ⚡ Client

- [x] Create a component to set up a flight.
- [x] On mounting component, al scripts should be fetched.
- [x]  Scripts should be options in select for script entry.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] User should be receiving feedback that reflects whether or not a script they entered lives in the database or not.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
