### ISSUE TITLE
Feature: User can create an e-mail within a script

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/Drip-Email-System#20]
## ⚙️ User can create an e-mail within a script.

> ##### What capability will users have when this feature is merged?
The user will be able to create an e-mail within a script. This means they will be able to create a scripted e-mail that will be attached to a script.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create an initial e-mail within a script.

This will contain 4 fields, 3 of which will be accessible to the user.

Name, Subject, Interval (will not be accessible, I'd like them to be aware of it though) and Body.

## 🖼️ Wireframes

![Feature 7 - User Can create an e-mail within a script](https://user-images.githubusercontent.com/51938797/120239718-bf06e780-c213-11eb-8889-b5b9dee38359.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create Emails Table.
- [x] Emails table should have an Id column to identify the email.
- [ ] ~~email table should have a name column that contains the name of the email. (text field - is this necessary?)~~
- [x] emails table should have a  subject column, that contains the subject of the e-mail. (text field) (The names of the e-mails will change as a user replys to an e-mail, and then another e-mail etc. This is dictated by the system being used, since they'll be replies to the initial e-mail. Since this is true, does this change anything?)
- [x] emails table should have a body column. This contains the text of the e-mail. (text field)
- [ ] ~~emails table should have an interval field. (Should this be a time field? Should this be specified in 24/36/48 hours, or in specific points of time in the future? Like - July 25th 2021 at 12:00:00 PM?) This field will be nullable, since the interval will be set on the subsequent e-mail. So for example - for e-mail 2 in a chain, it will be sent 24 hours after e-mail 1. The first e-mail will by definition not carry a value here.~~
- [x] emails table should have a scriptId column within it. This will specify which flight it belongs to. (Integer field)
- [ ] ~~emails table should have a 'initial email' indicating whether it is the first e-mail in a chain, or a reply. This field will be a bool field (bool field.)~~

### ☁️ Server

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Add a POST route that will initiate creation of E-mail.

### ⚡ Client

- [ ] Create a component to display the email creation form.

### Concerns
 Should there be two separate tables for e-mails? One containing core information like content - subject, body, emailId and then another table containing say "ScriptId, EmailId" and some other fields so that every time an e-mail is sent, a simple look up can be done in the second table, and then a cross reference to the first table for the contents of the e-mail? Not sure how to structure.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
