### ISSUE TITLE
Polish: Add and implement toastify

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/Drip-Email-System#24]
## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

Add and implement toastify so the user has a richer feedback experience from the system. It is too plain right now.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Show a loading spinner while the app is making requests for data.
- [ ] Spell-check and grammar-check all hard-coded text, like buttons, labels, and headings.
- [ ] Scrub all undesirable or unrealistic example data if using a database.
- [ ] When data fetching or search results lists are empty, show a message informing the user that there were no results found.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile (375px x 812px) and desktop (1280px x 720px) screens.
  - [ ] Confirm that resizing the browser window from mobile, to desktop and back does not look "broken" at any point.
  - [ ] Create GIFs of the app being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
