### ISSUE TITLE
Feature: User can assign a contact to a flight.

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/Drip-Email-System#28]
## ⚙️ User can assign a contact to a flight.
A user will be able to assign a contact to a flight.

Flights are the fundamental unit of functionality in this application. By assigning both scripts and contacts to them, a user can send e-mails out. By attaching contacts to a flight, we are adding a core piece of functionality to the component so we can send out e-mails.

## 📐 Functionality

Flights are the fundamental unit of functionality in this application. By assigning both scripts and contacts to them, a user can send e-mails out. By attaching contacts to a flight, we are adding a core piece of functionality to the component so we can send out e-mails.

## Plan of approach

Ideally there will be a search field that will allow the user to type out the name of a contact, and get some real time feedback as to whether or not the contact exists. Once the user has found the contact they are looking for, the contact will then be assigned to the flight by their contact Id.

Given that there is limited time, and much to do, I may not have time to explore a search field for contacts and learn how to do it, In this case, a dropdown select field will be best.

My thinking for this in terms of a plan, was to create a new table, that contained the flightId and the contactId. So that it will be easy to access, and add, who was assigned to what flight. These will both have key constraints on them from other respective tables, those being the flight, and the contact. 

Assuming this is the correct way, I will take the following approach:

 - Create new Table.
 - Insert dummy material into db.
 - Display dummy table via HTTPie.
 - Create a Post call.
 - Create new component for front end to manage a flight.
    - Set up hash routing functionality so component can be viewed.
    - Add prompts to choosing contacts.
    - Add Button.
    - Add form controls.

## 🖼️ Wireframes

![Feature 8 Photo](https://user-images.githubusercontent.com/51938797/120570721-91fe3480-c3cd-11eb-86dd-c2ee543a1722.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create flightAssignment table
- [x] Update `data.sql` to enter contacts into flightAssignment table.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Set up post request for insertion of data into this table.

### ⚡ Client

- [x] Create a component to manage a flight.
- [x] Update component to show a list of contacts assigned to flight.
- [x] Update component to show which script has been selected for flight.
- [x] Update component to render in real time additional clients.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
