### ISSUE TITLE
Design Update: Add a launched at column for flights table.

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/Drip-Email-System#52]
## ⚙️ Feature

> ##### Which feature is affected by this update?

## 📐 Plan

> ##### Summary of the technical approach to be taken.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
