### ISSUE TITLE
Feature: User can create script

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/Drip-Email-System#8]
## ⚙️ User can create a script

> ##### What capability will users have when this feature is merged?
A user will be able to create a script. A script is a repository for an e-mail chain. Scripts consist of 2 kinds of e-mails, initial e-mails, and responses to the initial e-mail. When this feature is created, the user will have the ability to _just create a script_ and nothing else. That means a record of the creation of a script will live in the database, a scriptId and a text string.

Creating a script does not entail the creation of an e-mail. An E-mail must be created within a script.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Plan is as follows:
 - Create DB. DB will have scriptId and scriptName (for now).
 - Insert dummy material into db.
 - Create POST call.
 - Test data.
 - Create new component.
  -  Create static Text that is the header of the component.
  -  Create React Element that outlines Form. Then create form.
  - Add text prompt for input field.
  - Add Button.
  - Add Form Control.
  - Check and conform form is submitting on back end.
  - Add clear form functionality to component.
  - Provide functionality around confirming/rejecting insertion of script.
 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Create_Script](https://user-images.githubusercontent.com/51938797/119873966-fc007080-bed9-11eb-8fdf-52ff2a05de9c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...
- [x] Script table should have an id column to identify script. (integer field)
- [x] scripts table should have a name column that contains name of script. (text field)

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] POST for insertion.

### ⚡ Client

- [x] Create a component to set up a script.
- [x] Develop form controls.
- [x] Develop clear form functionality. This should fire after a successful entry has been made.

### 🧑‍⚕️ Clean Up

- [x] confirm toaster works for success and rejection.
- [x] confirm form is cleared only if successful entry of information to db is made, not if failure.
- [x] Provide feedback to user so they know if post is accepted/rejected.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Ensure styling conforms to existing styling.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
